### ISSUE TITLE
HashMap实现方式写反

### ISSUE THREAD

**Issue by wddddw** [StackInk/MakerStack#8]
https://github.com/StackInk/MakerStack/blob/master/docx/%E9%9D%A2%E8%AF%95/Java%E5%9F%BA%E7%A1%8002.md#5hashmap-%E7%9A%84%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%90%86%E5%BA%95%E5%B1%82%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84jdk17-%E5%92%8C-jdk18

中，JDK1.7和1.8的实现反了~

1.8开始添加了红黑树

**Comment by StackInk** [comment]
fix 感谢老哥指出
